sudo: required

services:
  - docker

script:
  - docker --version  # document the version travis is using
  - docker build -t krysp89/hyperflow-worker-docker-test .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push krysp89/hyperflow-worker-docker-test

# safelist
branches:
  only:
  - feature/docker
